--Tạo metadata
use master 
go
if DB_ID('METADATA') IS NOT NULL
	DROP DATABASE  METADATA
GO
CREATE DATABASE METADATA
GO
USE METADATA
GO

DROP TABLE IF EXISTS DATA_FLOW

--DATA FLOW
CREATE TABLE DATA_FLOW (
	ID INT NOT NULL IDENTITY(1, 1),
	TABLE_NAME VARCHAR(50),
	LSET DATETIME,
	CET DATETIME,
	STATUS VARCHAR(30) DEFAULT 'UNDEFINED',
	ROW_COUNT INT DEFAULT 0,
)
GO

TRUNCATE TABLE DATA_FLOW

--INSERT DU LIEU VAO METADATA
INSERT INTO DATA_FLOW (TABLE_NAME, LSET, CET)
VALUES 
    ('US_COUNTIES', '2015-01-01 00:00:00', '2015-01-01 00:00:00'),
	('STATE_AQI', '2015-01-01 00:00:00', '2015-01-01 00:00:00')
GO

SELECT * FROM DATA_FLOW

SELECT LSET, CET
FROM DATA_FLOW
WHERE TABLE_NAME='STATE_AQI'



